#!/usr/bin/env python
# -*-python-*-

"""
./scripts/wof-update-meta -m /usr/local/mapzen/whosonfirst-data/meta/wof-microhood-latest.csv /usr/local/mapzen/whosonfirst-data/data/102/147/445/102147445.geojson
"""

import os
import sys
import logging

import mapzen.whosonfirst.meta

if __name__ == '__main__':

   import optparse
   opt_parser = optparse.OptionParser()

   opt_parser.add_option('-m', '--meta', dest='meta', action='store', default=None, help='The path to the meta file you want to update')
   opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')
   options, args = opt_parser.parse_args()

   if options.verbose:
      logging.basicConfig(level=logging.DEBUG)
   else:
      logging.basicConfig(level=logging.INFO)

   source_meta = os.path.abspath(options.meta)

   if not os.path.exists(source_meta):
      logging.error("meta file (%s) does not exist" % source_meta)
      sys.exit()

   dest_meta = source_meta

   mapzen.whosonfirst.meta.update_metafile(source_meta, dest_meta, args)
